environment:
  matrix:
    - PYTHON: "C:/Python27"

clone_folder: c:\projects\sphinx-docfx-yaml

install:
  # .NET
  - ps: (new-object net.webclient).DownloadFile('https://github.com/dotnet/docfx/archive/dev.zip', 'c:\projects\sphinx-docfx-yaml\docfx.zip')
  - cd c:\projects\sphinx-docfx-yaml
  - 7z e docfx.zip -oc:\projects\sphinx-docfx-yaml\docfx
  # Python
  - ps: (new-object net.webclient).DownloadFile('https://bootstrap.pypa.io/get-pip.py', 'C:/get-pip.py')
  - "%PYTHON%/python.exe C:/get-pip.py"
  - "%PYTHON%/Scripts/pip.exe --version"
  - "%PYTHON%/Scripts/pip.exe -q -q -q install tox sphinx msrest msrestazure sphinx_rtd_theme ."

build_script:
  - cd c:\projects\sphinx-docfx-yaml\docs
  - "git clone https://github.com/ericholscher/azure-sdk-for-python/"
  - cd azure-sdk-for-python
  - python setup.py -q install 
  - cd doc
  - "%PYTHON%/Scripts/sphinx-build.exe -b html -d _build/doctrees . _build/html"
  - c:\projects\sphinx-docfx-yaml\docfx\docfx.exe build

artifacts:
  - path: 'docs/azure-sdk-for-python/doc/'
